### ISSUE TITLE
email users when new dataset published/updated for spill response

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#102]
@genkimaps This was requested by some folks from spill response. There are 2 related requests
- [x] send email when a new dataset is published and added to gis-spill-response-go-kit group
- [x] send email when an existing dataset in gis-spill-response-go-kit group is updated 

I added some functions to ckanapi to make this work and the script in email_new_datasets.py in the GIS Hub repo is importing the ckanapi module. See https://github.com/genkimaps/hub-geo-api/commit/33ac087a33c85ce69792e263e6da60a8098756df, https://github.com/genkimaps/hub-geo-api/commit/4f723db1bd6ede92a686c42d3a99be831bc709c1, and https://github.com/genkimaps/hub-geo-api/commit/95da18a21b0cf9d8ad2bcc0ba80c1b3a814c7d7a. 

Also see the changes in this repo on email-spill-response branch  https://github.com/genkimaps/gis-hub/commits/email-spill-response.

I've added a cron job to `/home/dfo/dfo-crontab` and will see if everything works for emailing re new datasets. I've tested by manually running `./email_new_datasets.sh` after created a new test dataset today and adding it into the group. Some complications with time zones (UTC vs local time). Will need to implement a bunch of functions for the second part - updated datasets.

I think one change that might need attention is logging. I'm in a hurry but will add more details another day.

**Comment by cole-fields** [comment]
@genkimaps There are a few things going on here with this update.

1. For spill response, send an email to members of group https://www.gis-hub.ca/group/gis-spill-response-go-kit if a new dataset is created within the last 60 minutes _and_ added to the group.  Both conditions must be met. Datasets do not have to belong to the organization https://www.gis-hub.ca/organization/environmental-emergency-response since the group has datasets from several orgs.
2. Check all datasets on the hub. If any have resources that have been **updated** in the last 60 minutes, check for users following the dataset. If there are any, email them about the updated dataset. 
3. Check all organizations (except for Test org) for new datasets (last 60 minutes). If there are any, get the followers of the owner organization. Check for followers. If dataset is private, email only those followers who belong to the owner org. If dataset is public, send email to all followers about new dataset. 

I set up a cron job to run hourly - most of the time, there will be no updates or new datasets, so hopefully this doesn't use too many resources. Seems to only take about 10 seconds or so to complete. I merged the email-spill-response branch with master after some testing. Let me know if you see anything glaringly wrong with the code. I know there are a few places it could be improved, but seems to be working for now.

**Comment by genkimaps** [comment]
@cole-fields  Great work on this. At first glance this module you built looks fine. I think I can see a few places where the code could be simplified, but I haven't looked closely. And thanks for making sure that this doesn't interfere with other parts of CKAN.  

One thing to be aware of.  In CKAN, you can attach a trigger to events such as dataset / resource updated and execute any code from that event. In theory you could re-write this so that you don't have to poll hourly from cron. Example: https://github.com/genkimaps/gis-hub/blob/46f88671b3dd80ca6be7b238b05f4b2db212b76a/ckanext/dfo/plugins.py#L275

FYI I am still working on the Geoserver security issue, but made a lot of progress today. A functional solution is coming soon, I promise!

**Comment by cole-fields** [comment]
Awesome, thanks for the link to the after_update function. I will have to check that out. I imagine I'll have some revision of the code in the future - it kind of started simple (email spill responders) to a more broad task of emailing any followers of datasets or organizations after there are new or updated datasets. 

That's good news about the Geoserver security issue - thanks for making that the priority. I look forward to seeing/hearing about it.
