### ISSUE TITLE
Email data maintainers update

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#106]
- [x] check metadata to see if `Update Frequency` field is set to `Not Planned` or `As Needed` ~~or `Irregular`~~ before email users. The script runs monthly - could be annoying to receive every month if there are no planned updates.

Related issue: https://github.com/genkimaps/gis-hub/issues/82

**Comment by cole-fields** [comment]
@genkimaps this is an update to the SQL query to include the Update Frequency value in the csv file. The values in that column are then filtered in the dfo_data_maintainer.py script to remove and records where the Frequency is 'Not Planned' or 'As Needed' before doing further filtering.

**Comment by genkimaps** [comment]
@cole-fields Looks good, thank you for doing this.
