### ISSUE TITLE
Add dropdown links in nav bar

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#107]
- [x] Organizations
- [x] Groups
- [ ] Datasets (do it by themes maybe?)

**Comment by cole-fields** [comment]
@genkimaps the changes were made here: https://github.com/genkimaps/gis-hub/tree/dropdown and merged with master. So far, this is done for groups and organizations, and I had a thought of adding a dropdown under datasets that is a list of the dataset Themes (i.e. Base Mapping, Coastal Species, Protected Areas, etc). Took a bit of troubleshooting to make sure the links work on mobile. 

I also removed the About page from the nav bar since it was really about CKAN, not the GIS Hub and i didn't think it was super relevant, but let me know if you think otherwise.

**Comment by cole-fields** [comment]
not going to add themes at this point since that's already a sidebar filter and having the groups and orgs is pretty sufficient for now

**Comment by genkimaps** [comment]
@cole-fields This looks great, thanks for taking this on. Dealing with the CKAN templates can be a hassle sometimes.
