### ISSUE TITLE
Add a server maintenance page for downtime

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#108]
https://serverfault.com/questions/310819/maintenance-page-on-nginx-best-practices

**Comment by genkimaps** [comment]
@cole-fields  This is a good idea, and it should not be too much work to implement. My apologies for the very slow reply on this. I'm making a real effort to get back to all of my clients much faster.

**Comment by genkimaps** [comment]
@cole-fields  This was a fairly easy change. If CKAN is down, it causes a 502 error, which is redirected to an error page: https://github.com/genkimaps/gis-hub/blob/4e64cabd3d2780af8604c5a49228a677c949a904/conf/dfo.gishub.nginx.conf#L122

We can customize this error page if you like.  Just a generic page for now.

**Comment by cole-fields** [comment]
@genkimaps I tested this out and it works perfect - thanks for taking care of that! For now, I'm happy with the existing message about server maintenance.
