### ISSUE TITLE
Redirect login URL from /dashboard to root (gis-hub.ca)

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#113]
When a user logs in, they are directed to the dashboard page. We want to modify this so that they are redirected to the home page gis-hub.ca. This will improve performance speed because it will reduce the # of API calls for checking the permissions of the user against datasets/resources when generating the entries on the dashboard page.

**Comment by cole-fields** [comment]
In the `who.ini` file, there is a parameter `post_login_url = /user/logged_in`. I think that variable get's passed to core ckan's /lib/repoze_plugins/friendly_form.py, and is used here: https://github.com/ckan/ckan/blob/ca4d764f25f3378b083fa1e0b6b9f67be4c44864/ckan/lib/repoze_plugins/friendly_form.py#L170 to create a new destination. 

I could be totally off on this, but didn't want to spend too much time in case you already knew how to alter this.

**Comment by genkimaps** [comment]
@cole-fields Very useful, thanks. I'll try changing that as the first step.

**Comment by cole-fields** [comment]
Ah right, not what we want for sure. It would be great if this was just a parameter set in the config file. But it looks like it's somewhat buried!

**Comment by genkimaps** [comment]
@cole-fields  Went digging a bit more and I found this: https://github.com/g-rock/ckan/commit/6edfb7b900fe5aa5f80989492893ba5b3fd4a4dc

There is a config option in the CKAN ini file: `ckan.route_after_login` 
However, this was added to CKAN only in 2019, and the file in question `/ckan/views/user/py` does not exist at all in the version of CKAN we are using.  I'm reluctant to try to patch our version, instead we should probably have a long-term plan to eventually upgrade to the latest CKAN (which runs on python3, better security, etc).

**Comment by cole-fields** [comment]
Thanks for checking in on this. I agree, the migration to a newer version of CKAN that runs on py3 has been in the back of my mind for a while. Because of the extensions the hub uses, I get the feeling it could be quite a bit of work.

**Comment by cole-fields** [comment]
@genkimaps I've updated https://github.com/ckan/ckan/blob/ff966dc043d2203062f2ed8de2a470bd92058cb7/ckan/controllers/user.py#L153 on our ckan instance to render the homepage after a user logs in rather than redirect to the dashboard page. Clicking on a users dashboard still works and will bring them to the correct link. Logging in seems quite a bit faster now. Since the core ckan on the server is not a git repository, I backed up user.py and modified the source file as follows (just added in return render(...).


    def me(self, locale=None):
        if not c.user:
            h.redirect_to(locale=locale, controller='user', action='login',
                          id=None)
        user_ref = c.userobj.get_reference_preferred_for_uri()
        return render('home/index.html')
        #h.redirect_to(locale=locale, controller='user', action='dashboard')

**Comment by genkimaps** [comment]
@cole-fields  That's great, thank you for tracking this down.  That part of CKAN is kind of a rat's nest.  Ideally this should be done through an extension that overrides `class UserController(base.BaseController)` in the user.py file.  This is an example that just might work:

https://github.com/okfn/ckanext-example/blob/master/ckanext/example/controller.py

**Comment by cole-fields** [comment]
That's a much better idea than just modifying the source code - I was being a bit lazy there and hadn't implemented something like that before so thanks for linking the example code. I've gone ahead and added a controller.py file and updated the plugin.py file to reroute users to the homepage once they are logged in.

**Comment by genkimaps** [comment]
@cole-fields  Perfect, thanks for adding that to the extension.  That's pretty much exactly how I would have done it.
