### ISSUE TITLE
Notify if instance is not running

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#114]
We can use one of the many ping services to check this, completely independent of AWS.  Set this up for both GIS Hub and mapserver.

**Comment by genkimaps** [comment]
@cole-fields I put these under monitoring in statuscake.  I think that's preferable to using AWS alarms, which can be difficult to configure.  Also it is possible that if a VM goes down, the AWS alarm system might also go down at the same time.

**Comment by cole-fields** [comment]
It must be Monday morning since I spent some time trying to figure out where statuscake was installed on the servers. But now I realize that doesn't make sense and that this is an external service that will ping the server(s) and send emails if they're down - I received a couple that I assume were from testing. Thanks for setting this up. Should I have the login or are you using that service for other projects and can't share?

**Comment by genkimaps** [comment]
@cole-fields  I have a few of my own projects in my statuscake account. However, there is nothing stopping you from making your own statuscake account and adding these servers.  Unlike mailgun, there is no concept of a single account "owning" a given domain.  In fact it's probably a good idea to have your own account there anyway.  Once you do that and ensure it's working, I can remove your email address from the mailing list in my account. 

A few years ago I used a service called Pingdom, but they got greedy and removed their free plan.

**Comment by cole-fields** [comment]
Right, that makes sense. I set up an account on statuscake and added the 2 domains (gis-hub.ca and maps.gis-hub.ca) under uptime monitoring. Do you just add them as the http type or another?

**Comment by genkimaps** [comment]
@cole-fields Sorry for the late reply. 

>  Do you just add them as the http type 

Yes. However, in mapserver I had to make a small change, because all HTTP connections to the `/geoserver` path are now blocked except from gis-hub.ca. I added this line in the mapserver nginx config: `root /home/dfo/mapserver/public;` which tells it to serve static HTTP files from that location, and I also added a blank html page index.html in the public folder. So you can point statuscake to https://maps.gis-hub.ca/ and you'll get an empty page, which is fine for status checking.

**Comment by cole-fields** [comment]
@genkimaps ok, understood. Thanks for clarifying. I've got my account set up and pointing to the 2 URLs now.
