### ISSUE TITLE
Cleanup log files

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#116]
For all repositories in GIS Hub that write to a log file, ensure that the logs are being rotated.  Also check log rotation settings for processes under supervisor.

**Comment by genkimaps** [comment]
Logs for the following extensions are now set to rotate at midnight: 
- ckanext-dfo
- ckanext-restricted
- hub-geo-api

Logs for ckanext-scheming were turned off completely, since they were only used for debugging in the past, no longer needed.

**Comment by genkimaps** [comment]
For processes under supervisor, the default log rotation setting is to rotate when the logfile exceeds 50MB. This can be seen for the solr logs in `/var/log/supervisor`.  None of the other logs have reached that size yet. This seems like a reasonable default. 

See this page: http://supervisord.org/configuration.html#program-x-section-values
Under section `stdout_logfile_maxbytes`.

**Comment by cole-fields** [comment]
Great, this looks like a clean solution to prevent any really large log files. Thanks for updating that. Interesting to take a browse at the different handlers that are available for logging.

**Comment by genkimaps** [comment]
Log file rotation still working, closing this.

**Comment by cole-fields** [comment]
@genkimaps there is some inconsistency with the log files that was resulting in a file permission error and the site crashing (i.e. `IOError: [Errno 13] Permission denied: '/home/tk/ckanext-dfo/ckanext/dfo/logs/dfoext.log'` from ckan logs. Looking at the stored log files, some are created with the owner as tk and some as dfo. The site was running today, and I restarted ckan as usual using supervisorctl and then the maintenance page was displayed. So after checking the log files, I changed the owner of the rotated log file `/home/tk/ckanext-dfo/ckanext/dfo/logs/dfoext.log` to tk and then restarted ckan which did the trick. 

I added a shell script here: https://github.com/genkimaps/gis-hub/commit/f0baefc26d5834dc64c883e7aebb376ee250704e to run one minute after midnight after the logs are rotated to change ownership to tk. 

Looks like there is another method here: https://docs.python.org/3.5/howto/logging-cookbook.html#customizing-handlers-with-dictconfig to change ownership when creating the log file, but this seemed simpler. let me know if I've missed something or this is not a good solution. I haven't confirmed if it works on the actual log file yet but can check tomorrow.

**Comment by genkimaps** [comment]
@cole-fields  This is really bizarre, I can't understand why some of those log files are created with owner `dfo:dfo` instead of `tk:tk`.  CKAN should only be running through supervisor, and the supervisor config runs ckan under the tk user.  By contrast, all log files for the restricted extension are owned by `tk:tk` as expected (see `/home/tk/ckanext-restricted/ckanext/restricted`). 

The cron solution is a hack, but if it works, that's fine with me.

**Comment by cole-fields** [comment]
It looks to have worked for now - I can't guess at why some log files are create with the owner `dfo:dfo` and not `tk:tk`. I agree this is not the best solution, but for now, it seems to be working.

**Comment by genkimaps** [comment]
@cole-fields  All of the log files in `/home/tk/ckanext-dfo/ckanext/dfo/logs` since Aug 31 have owner `tk:tk` which is what we are expecting.  Will close this issue for now.
