### ISSUE TITLE
SSL Cert renewal failed

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#118]
@cole-fields  SSL certificate for the gis-hub site is now expired. When I run the renewal command manually:

`sudo certbot --nginx`

The server experienced an internal error :: ACMEv1 is deprecated and you can no longer get certificates from this endpoint. Please use the ACMEv2 endpoint, you may need to update your ACME client software to do so. Visit https://community.letsencrypt.org/t/end-of-life-plan-for-acmev1/88430/27 for more information.

Need to fix this ASAP,

**Comment by cole-fields** [comment]
Thanks for taking care of this while I was away - the timing wasn't great! I didn't receive any emails either, so I've added my gmail address using the certbot commands listed above for gis hub and mapserver. 

#### To manually check dates for my reference:
GIS Hub: 
`sudo openssl x509 -noout -dates -in /etc/letsencrypt/live/gis-hub.ca/cert.pem` 

Mapserver:
`sudo openssl x509 -noout -dates -in /etc/letsencrypt/live/maps.gis-hub.ca/cert.pem`

I've added a reminder in my calendar to check these before Nov 24.

**Comment by cole-fields** [comment]
closing this as you've upgraded certbot on the gishub server and it's ok on mapserver, and i have a calendar reminder as well now.
