### ISSUE TITLE
email data maintainer failing

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#129]
Monthly script to email data maintainer about datasets that have not been updated in over 365 days did not run.

Related: https://github.com/genkimaps/gis-hub/issues/106 & https://github.com/genkimaps/gis-hub/issues/82

**Comment by cole-fields** [comment]
I think this is because of env variables now being in a .env file, and not accessible through `os.environ.get` before loading in the .env file. I don't want to duplicate the .env file from the hub-geo-api (where it is currently), so I will reference that file.

Example:
`server = smtplib.SMTP(host=os.environ.get("CKAN_SMTP_SERVER"))`

Loads nothing since that variable is no longer defined in env vars on the system. This might be affecting other components or functions on the platform.

**Comment by cole-fields** [comment]
This is also in `./ckanext/dfo/new_updated_datasets.py:`.

**Comment by cole-fields** [comment]
Seems to be resolved now.

**Comment by cole-fields** [comment]
for my notes: changes were made on dotenv branch which is now merged w/master

**Comment by genkimaps** [comment]
@cole-fields A follow up to point out something in Git that I haven't encountered until now. I was going to remind you to delete the dotenv branch if you don't need it anymore. On my workstation, I ran the command to list all branches: 

`git branch -r`

This brought up a list of a couple dozen branches, most of which have been deleted. The default in Git is to continue displaying deleted branches on the remote, which is strange: https://stackoverflow.com/questions/17128466/why-do-i-see-a-deleted-remote-branch. To make it clear, these branches don't exist on the remote location (Github) and they have been deleted, but they still show up in my local Git. 

Can prune these branches from your local Git with:

`git fetch -p`

Test run to show which branches would be pruned:

`git remote prune -n origin`
