### ISSUE TITLE
Add an analytics page

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#135]
Some similar functionality to the https://www.gis-hub.ca/stats page. 

Plots/charts for:

- [x] most visited datasets
- [x] datasets published by year
- [x] number datasets by topic or category
~~- [ ] file formats~~
- [x] publishers (organizations)
- [x] top keywords

Can use Google Charts: https://developers.google.com/chart for free. 

Example with some dummy data from guide:

![image](https://user-images.githubusercontent.com/52669482/143510685-5b8b65ad-8cf3-4f81-bdf2-4b8d7a9dddd7.png)

**Comment by cole-fields** [comment]
@genkimaps Just an FYI, I have the GIS Hub temporarily running on analytics-page branch. I had worked on this in the code-modernization branch, which uses Flask/Blueprints and so I migrated some of that over for CKAN2.7 and Pylons/iRoutes. I'm going to make sure the cron job works (runs at 12:30 AM) to execute a python script that uses the CKAN API to query the datasets and export csvs after filtering and manipulating them into lists of dictionaries. 

I will merge with main branch soon unless you see a reason not to.

**Comment by cole-fields** [comment]
@kaylgill Another FYI: I added in an analytics page on the site with some charts that render on the page. I also moved the summary documents to this page. Just tagging you since you are in-the-loop with these updates. And let me know if you have ideas for improvements or if you catch any errors.

**Comment by genkimaps** [comment]
@cole-fields Looks great, thank you for creating this. I'm fine with merging this code to master, as long as you're sure that all of the routes work.  I haven't looked closely at the code but I will do so this week.
