### ISSUE TITLE
Delete orphan resources from S3

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#138]
Datasets that are marked as 'deleted' on GIS Hub should have the zip file resources deleted from S3. 
- [x] Make copy of a few of them first (the CHS datasets)
- [x] Identify datasets marked as deleted 
- [x] Delete resource (zip file) from S3 bucket

**Comment by cole-fields** [comment]
@kaylgill An FYI for you... datasets that are marked as deleted on the gis hub create these orphaned objects in S3 (the resources that were uploaded for the deleted datasets). At some points, we can go on the management console and into the pacific-gis-hub bucket then search by the values in the res_id column to delete. Some datasets that were deleted never had resources uploaded and so there is no object to delete. 

I don't really want to automate this and risk deleting everything accidentally. I will chip away at these during downtime since it's a low priority task. Just data taking up extra space.

[objects_to_delete.csv](https://github.com/genkimaps/gis-hub/files/7917024/objects_to_delete.csv)

**Comment by kaylgill** [comment]
Okay, thanks @cole-fields. That is good to know. I'm definitely interested in taking a look before we delete them all (to access the old CHS datasets for example), but at least the ones with no resources are good to go!

**Comment by cole-fields** [comment]
Note: since we use versioning in S3 bucket, the objects are marked with a delete marker, but are still retrievable (not fully deleted from AWS S3). 

At some point, we should have a strategy for completely deleting data from S3 and GIS Hub, and possibly transition some objects in S3 to a different storage type (glacier archive). However, we are still dealing with a relatively small volume of data and the cost is pretty low. So not a priority. 

I've 'deleted' the entries in the csv on the console.

**Comment by genkimaps** [comment]
Just to add a comment--I believe there is an option in ckanext-cloudstorage to delete objects from the cloud when a resource or dataset is deleted. However as you said, you might not want to automate this completely.
