### ISSUE TITLE
Restrict keywords and autocomplete to goc-themes

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#22]
There is a dataset containing all of the usable keywords at https://www.gis-hub.ca/dataset/goc-themes. We would like to restrict entry of keywords to these values. The autocomplete should show only the values that are in the goc-themes list. If a user types a different keyword, it should not allow it to be added to the list of keywords (and also it should not be added to the autocomplete entries).

**Note:** this is only for non-science (general) keywords.

The original list of GoC themes can be found here: http://canada.multites.net/cst/def.asp?lang=En&n=EAEAD1E6-1.  This is a complete ontology with multiple entries for each keyword including related terms, category, and relationships to other keywords / concepts.  I simplified this down to a flat list of keywords.

**Comment by mapgeek37** [comment]
There is a dataset containing all of the usable keywords at https://www.gis-hub.ca/dataset/goc-themes.  We would like to restrict entry of keywords to these values.  The autocomplete should show only the values that are in the goc-themes list.  If a user types a different keyword, it should not allow it to be added to the list of keywords (and also it should not be added to the autocomplete entries).

**Comment by genkimaps** [comment]
@cole-fields Although I still have not been able to get the Keywords autocomplete to be restricted to the GoC themes, I was able to create a _validator_ that will reject any keywords not in the GoC themes list.  See this: https://github.com/genkimaps/gis-hub/blob/a9a2d2f709114a1da5a40c988d1d70bd393744d0/ckanext/dfo/plugins.py#L166

This change is now live on gis-hub.ca

**Comment by genkimaps** [comment]
There are two possible sources for a custom autocomplete in CKAN:

1. a dataset with a datastore, which we already have at https://www.gis-hub.ca/dataset/goc-themes. We tried connecting this to autocomplete using `choices_helper: scheming_datastore_choices` in the schema file. This works for a single drop-down list, but not if we are trying to add multiple items in a field. 
2. a vocubulary. The CKAN documentation is thin on the ground when it comes to creating and maintaining vocabularies (https://docs.ckan.org/en/2.8/maintaining/tag-vocabularies.html), but I was able to figure out how to create a vocubulary and added some test keywords to it. This is at: https://www.gis-hub.ca/api/3/action/vocabulary_show?id=weather.  I was also able to setup the autocomplete API to query against this vocabulary: https://www.gis-hub.ca/api/3/action/tag_autocomplete?vocabulary_id=weather&query=sun.  However, I have not been able to successfully connect the frontend Javascript autocomplete widget to this API endpoint. Specifically, I am using the select2 Javascript module for this, and I include the JS module as a required item in the form template.  However this does not work, when trying to activate the `select2()` function on the form element, the browser throws an error (which can be seen in the developer console). Not sure what to do about this, the error message did not turn up anything useful. 

A few months ago on the CKAN gitter chat room (https://gitter.im/ckan/chat), someone else was asking about this exact issue:

can I tell the CKAN tag autocomplete API , to use a particular vocabulary?
reading over the code of the API, my half-educated guess is no .
@wardi @amercader ^

Ian Ward @wardi Jun 06 2019 04:36
you'd have to add a parameter to the action and submit a PR for it. That code could use some love, I stopped using vocabularies because of some of their language and performance limitations

Sivan Grünberg @sivang Jun 06 2019 04:39
so you just pile it all up in the tags field and somehow filter them out when you want to have a tag field that's not just the 'main' one?

Ian Ward @wardi Jun 06 2019 04:39
no I use scheming fields instead of tags
the choices for each field are part of the dataset schemas

Sivan Grünberg @sivang Jun 06 2019 04:41
right, the problem is that the autocomplete api just gives the "main" tag field , so even if I use a field like that and I want to use the autocomplete feature, I never see those tags in the speed search ui ... does that make sense?
s/tags/choices/g :)

Ian Ward @wardi Jun 06 2019 04:43
that's right, there's no handy autocomplete api for scheming choices, closest thing is the scheming_field_choices helper that gives you all the choices as a dict

Sivan Grünberg @sivang Jun 06 2019 04:45
I'll try go and jot my own autocomplete JS trying to generalize it and consume data from scheming_field_choices and if it's good, I can PR it so you can merge for the benefit of future scheming user next generations :)

Ian Ward @wardi Jun 06 2019 04:46
for sure, a JS autocomplete field for scheming choices would be nice

**Comment by genkimaps** [comment]
> Maybe the imported select2.js module is conflicting with the one that comes with CKAN and is built-in to fanstatic? 

Try referencing select2 from an external site.  Looks like this is possible, despite what the CKAN docs say. You can simply include a JS file as usual in your html template: `<script src="https://some-external-cdn.com/my-js-module.js"></script?`

**Comment by genkimaps** [comment]
@cole-fields  I finally cracked number 2, but it's an ugly hack. The autocomplete javascript module in CKAN seems to be missing the normal option in select2.js to get a list of autocomplete suggestions from a custom API endpoint.  The API endpoint has to use the version 2 API, which unlike the version 3 API, is not extensible. This means I had to do an ugly hack using the core CKAN code, in file `/ckan/ckan/views/api.py`.  It worked on my development machine, but does not work in production. 

Meanwhile, I created a new vocabulary containing only the GoC themes: https://www.gis-hub.ca/api/3/action/vocabulary_show?id=goc_themes 
Not all of the themes are in there yet, a number of them failed because they contain non-alphanumeric characters. 

`'error': {'name': ['Tag "Women\'s equality" must be alphanumeric characters or symbols: -_.']`


It is easy to query this vocabulary as follows:
https://www.gis-hub.ca/api/3/action/tag_autocomplete?vocabulary_id=goc_themes&query=act
However, the version 3 API returns a JSON data structure that is not compatible with the autocomplete module.  To work with the autocomplete module, we need a data structure like this: https://www.gis-hub.ca/api/2/util/tag/autocomplete?incomplete=ocea

The hack is in this branch https://github.com/genkimaps/gis-hub/tree/vocab-autocomp, but not deployed for now.  It causes production to crash, can't immediately see why.   There's all kinds of other weird stuff in here that is undocumented in the CKAN docs.  Had to do a lot of reverse engineering on this, but very close now.

**Comment by cole-fields** [comment]
thanks for the update - sounds like you're on the right track and very close. i wouldn't have guessed the process would be this complicated - appreciate the effort in digging in to it.

**Comment by cole-fields** [comment]
@genkimaps the general keywords auto-complete is listing entries from the science keywords vocabulary when entering them. this is confusing for users because it makes it look like these are valid GOC thesaurus entries. only when they submit do they see the error message and then a large portion of the metadata they entered in various fields is gone after the page refreshes

**Comment by genkimaps** [comment]
@cole-fields 
That's super annoying. Really sorry about this. Unintended consequences.

**Comment by genkimaps** [comment]
@cole-fields 
Big progress on this today. Working on option 1 (Try referencing select2 from an external site) and in the process I managed to reverse-engineer a lot of the autocomplete stuff.  I have a much better solution now that does not rely on ugly hacks.  Have not yet tried setting this up in production, will do soon. Stand by

**Comment by genkimaps** [comment]
@cole-fields 
I have tested this and it looks like it's working the way we expected. Finally.  All changes are in this branch: https://github.com/genkimaps/gis-hub/tree/goc-theme-autocomp.  It is using the CKAN API the way we expect, with the version 3 API (instead of version 2, which is not designed to be extended, and required an ugly hack).  In addition, I am not using the 'vocabulary' feature at all (which is poorly-documented and troublesome), instead there is a database query made directly on the table of GoC themes.  

The problems I was having earlier were because I did not notice that CKAN comes bundled with an older version of Select2.js (documented here: http://select2.github.io/select2/) and trying to shoehorn a newer version of Select2 into the HTML templates did not work.  I finally managed to reverse engineer the functionality that we need for the older version of select2 and get it integrated with the CKAN form templates.  See this file: https://github.com/genkimaps/gis-hub/blob/goc-theme-autocomp/ckanext/dfo/fanstatic/ac_goc_themes.js.  This piece of Javascript sends the characters typed by the user to the autocomplete API for GoC themes, and returns a list of matching terms.  

List of GoC themes is here: 
https://www.gis-hub.ca/dataset/goc-themes/resource/88f5c7a2-7b25-4ce8-a0c6-081236f5da76

Autocomplete API that queries the list of GoC themes:
https://www.gis-hub.ca/api/3/action/ac_goc_themes?q=car
The autocomplete suggestions work as expected, by returning matches at the start of the term, and not matches that merely contain the term in the middle of the word. 

I also updated the help text that goes with this field, and added more notes about it in the documentation. Please see the section on Keywords (GoC Thesaurus): 
https://www.gis-hub.ca/docs

I only had to make one small change in the core CKAN code, which is actually optional--to allow non alphanumeric characters (some of the GoC terms include apostrophes, for example).  In base ckan, `/ckan/logic/validators.py` comment line 460:
`# tag_name_validator(tag, context)`

Big picture: see this wiki page on keywords issues: https://github.com/genkimaps/gis-hub/wiki/Keywords-Issues.  Everything there is resolved except for the Species Code autocomplete.  I think I can use a similar mechanism to resolve that one, too.

**Comment by cole-fields** [comment]
@genkimaps excellent, this is very helpful. Thanks for updating the docs and the helper text - this should make it really simple for users when creating new datasets and avoid the confusion from the autocomplete pulling from all the keywords. Nice work! I haven't looked into the details here yet, but seems like substantial effort to figure out - appreciate the solution

**Comment by genkimaps** [comment]
@cole-fields Yes this was a lot of trial and error, but finally working the way we want. Closing it now.
