### ISSUE TITLE
Add autocomplete to each contact field

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#42]
Show Contacts as a drop-down menu, similar to organizations, with autocomplete on the contact person's name.  When a user is selected from the menu, contact info fields (phone, email, etc) should be populated on the form.  

Also needs to support adding a new contact (by filling in the fields for name, phone, email and so on).  This can be implemented with a "previously-seen users" table.   Some of the contacts are external people who do not have a CKAN account, so we can't use the built-in CKAN Users table for this. 

**Maybe change to**:  Add auto complete to each contact field independently?

**Comment by cole-fields** [comment]
@genkimaps I think given our discussion last meeting, we decided to change this to autocomplete. no need for a full-fledged drop down given the work involved

**Comment by genkimaps** [comment]
This will need to be done with a query to Solr, since the contact fields are not loaded into datastore tables.  Something like this: 

`packages = toolkit.get_action('package_search')(
        data_dict={'q': 'extras_creator_name:*<query>*',
                   include_private: True})`

Then iterate all matching packages, get list of creator_names, return as list to autocomplete JS.  Somewhat awkward, but it should work.

**Comment by cole-fields** [comment]
Right, thanks for looking into this. It is not a high priority - users may even be copying & pasting metadata from the docx template anyways. It's sort of a nice-to-have feature, but if the query is slower than people typing, then may not be usable as you say.

**Comment by cole-fields** [comment]
@genkimaps since querying on this field is fairly slow, I think we can close this issue.
