### ISSUE TITLE
Dashboard error when following MSEA organization

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#52]
When following the MSEA organization, with the ckanext-restricted plugin enabled, try to access the dashboard page and get this error.  This does not occur when you follow any other organization, user, or dataset. Also does not occur when ckanext-restricted is disabled. 

`URL: https://www.gis-hub.ca/dashboard
...
File '/home/tk/ckanext-restricted/ckanext/restricted/action.py', line 93 in restricted_package_show
  package_metadata = package_show(context, data_dict)
File './ckan/logic/action/get.py', line 1015 in package_show
  package_dict = model_dictize.package_dictize(pkg, context)
File './ckan/lib/dictization/model_dictize.py', line 218 in package_dictize
  lambda x: x["name"])
File './ckan/lib/dictization/__init__.py', line 78 in obj_list_dictize
  obj, capacity = obj
ValueError: too many values to unpack`

**Comment by genkimaps** [comment]
Further testing showed that this error was caused by incomplete metadata in some resources in our datasets.  In particular, some resources were auto-created by the hub-geo-api Python app in the background of the GIS hub, which reads the contents of uploaded files.  This app creates additional resource entries for files including pdf, word documents, and other recognized formats.  The resource entries are created from a template, but this template was missing the `restricted` field in the metadata, which is required by the CKAN restricted extension. For some reason, this does not cause any problems when viewing the resource page itself, only when viewing the Dashboard.  This is probably because the CKAN restricted module also handles request to the dashboard page and tries to limit the entries shown on the dashboard to those resources that a user has access to.  If a resource is missing the `restricted` field, it crashes. 

The fix is to update the code in hub-geo-api to add that field to the template, and also to update all existing resources for which that field was missing. This is done here: 
https://github.com/genkimaps/hub-geo-api/commit/7175183e8b9043486e5ff30577d99cb6bd7b585a

**Comment by genkimaps** [comment]
This issue recurred in the goc-themes dataset.  For some reason, the value in restricted was set to: 
`"restricted": "{'allowed_users': u'', 'level': u'registered'}"` 
with single-quotes around the keys in the nested json.  It is supposed to be:
`"restricted": "{\"allowed_users\": \"\", \"level\": \"registered\"}"`

**Comment by genkimaps** [comment]
Discovered that the API call I was using to iterate all datasets actually did not include private dataset.  The updated API call is documented in the wiki.  When I ran script to fix missing / invalid "restricted" fields while including private datasets, I found some that needed to be fixed. This may have been the smoking gun that caused this issue to recur. Since I added the  try-except block, it probably does not matter anyway.

**Comment by cole-fields** [comment]
> When following the MSEA organization, with the ckanext-restricted plugin enabled, try to access the dashboard page and get this error. This does not occur when you follow any other organization, user, or dataset. Also does not occur when ckanext-restricted is disabled.
> 
> `URL: https://www.gis-hub.ca/dashboard ... File '/home/tk/ckanext-restricted/ckanext/restricted/action.py', line 93 in restricted_package_show package_metadata = package_show(context, data_dict) File './ckan/logic/action/get.py', line 1015 in package_show package_dict = model_dictize.package_dictize(pkg, context) File './ckan/lib/dictization/model_dictize.py', line 218 in package_dictize lambda x: x["name"]) File './ckan/lib/dictization/__init__.py', line 78 in obj_list_dictize obj, capacity = obj ValueError: too many values to unpack`

I haven't encountered the dashboard error recently.
