### ISSUE TITLE
Save all of Tyler's customizations

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#54]
Tyler (tk-tech) made a number of customizations to CKAN in places **other than** the DFO ckanext-dfo extension.  For example, he made some custom changes in the ckanext-scheming extension, among other things adding a custom validator for us `require_when_published`. (This validator allows a field to be blank when a data is in a draft state (i.e. Private) but requires the field to be filled in before the dataset can be made public).  When trying to run a local copy of the GIS hub for testing, I am running into all kinds of crashes because of this, like the following:

`SchemingException: validator/converter not found: 'require_when_published'`

I have been using the published version of the ckanext-scheming extension from Github, which would be ok except that Tyler **never pushed his customizations to Github** for this extension and others where he made custom changes.  In fact, he never used git on the production version of this code, so it's very hard to tell where the differences in the code are.  This is very, very bad practice.  Of course, we do have the source code for this, I can fetch it from the gis-hub server and integrate the changes, but still...

Todo for this task is to scp all of Tyler's production code, ensure that all of these have a git repo so that we can track changes, and go from there.

**Comment by cole-fields** [comment]
appreciate your use of git-hub to track all of these issues.

**Comment by genkimaps** [comment]
@cole-fields 
I confirmed with Tyler which CKAN extensions have customizations that were specifically for DFO (other than the main ckanext-dfo extension containing most customizations, which is this repository).  They are:

**ckanext-restricted**
This extension allows files uploaded to a dataset to have download access restricted to a subset of users/organizations.
On the server at: `/home/tk/ckanext-restricted`
Github: https://github.com/genkimaps/ckanext-restricted

**ckanext-scheming**
Extension for customized metadata schemas. 
On the server at: `/home/tk/ckanext-scheming`
Github: https://github.com/genkimaps/ckanext-scheming
