### ISSUE TITLE
Update mailgun account info

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#56]
Current gishub config uses a mailgun account owned by Tyler. Change this to a mailgun account that we control.  This also requires that we change the mailgun key in the DNS settings in Amazon AWS, and then verify this domain in mailgun. Once this is done, ensure that email notifications in CKAN are working, and test sending notification from CKAN (also document here how this part is done).  

The mailgun settings are in the CKAN ini file:
`/home/tk/ckan/dfo.ini` 
Look for settings 
`smtp.server` and so on.

**Comment by genkimaps** [comment]
DNS records in Amazon Route 53 are currently connected to Tyler's mailgun account. We want to move this to our mailgun account. Looks like the only parameter we need to change is the RSA key that mailgun uses to verify domain ownership.  

In case we need to restore it, Tyler's key is: 
`k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDUza+c3Q6Gdo6Ktv8zP1ZrWKaoJnvA8KxygK3QI4ZMelt+eJwVBs7hwR6hFW0k/35lqEWUMAUH1lvzzGHc2EE+rCXW2NJOk38B3ZVsOQ1JxGLhWYY+ZzWDiAriAByJomTWNThK82+sFSSCauDAGayn3JbAYhwXcLHpBWC2426HwwIDAQAB`

This will be changed to the RSA key in my mailgun account.

**Comment by cole-fields** [comment]
@genkimaps I tried creating an account for a new user today, and got the error below:
![mailgun](https://user-images.githubusercontent.com/52669482/79495171-0b27a600-7fd9-11ea-977f-0e02350cdea8.PNG)

I was able to add the user manually in the database no problem, but this highlighted an issue with mailgun. As far as I can tell on the Route 53 management console, Tyler's key is still being used. I'm guessing maybe something has expired or he has disabled something on his mailgun account? Should I create a mailgun account? Or is it possible to link me to yours similar to AWS console? 

![image](https://user-images.githubusercontent.com/52669482/79495055-e03d5200-7fd8-11ea-99a8-c833c8021f56.png)

**Comment by genkimaps** [comment]
@cole-fields If you look at the previous message, I already have a mailgun account, but I was not able to switch the domain from Tyler's account to my account. Possibly this is because I was trying to use the same subdomain: mx.gis-hub.ca, which is already registered.  Might work if we use a different subdomain, like mail.gis-hub.ca.

**Comment by genkimaps** [comment]
@cole-fields  Cole: I just tried using mail.gis-hub.ca with my mailgun account, and it worked--I successfully sent a sign-up email to myself.  It's now completely disconnected from Tyler's mailgun account.  

Download a copy of the CKAN ini file (`/home/tk/ckan/dfo.ini`) and check the section "Email settings"

**Comment by cole-fields** [comment]
@genkimaps ok, great. it still looks like we're using Tyler's public key on Route 53 console though?

> In case we need to restore it, Tyler's key is:
`k=rsa; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDUza+c3Q6Gdo6Ktv8zP1ZrWKaoJnvA8KxygK3QI4ZMelt+eJwVBs7hwR6hFW0k/35lqEWUMAUH1lvzzGHc2EE+rCXW2NJOk38B3ZVsOQ1JxGLhWYY+ZzWDiAriAByJomTWNThK82+sFSSCauDAGayn3JbAYhwXcLHpBWC2426HwwIDAQAB`

https://console.aws.amazon.com/route53/home?region=ca-central-1#resource-record-sets:Z3LUBHUCQYJ8IM

**Comment by genkimaps** [comment]
@cole-fields Tyler's mailgun key is still associated with the subdomain mx.gis-hub.ca on Route 53, but the new mailgun info is on subdomain mail.gis-hub.ca.  I left the old DNS settings there in case we needed them, but they can now be removed.
