### ISSUE TITLE
Keywords should be case-insensitive

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#57]
In CKAN's keyword system (aka "tags") the following keywords are all different:

IMPORTANT AREAS
Important Areas
important areas

For our use case, keywords should not be case sensitive.  This will probably require creating a custom keyword management system that replaces CKAN's default tag system. 

The autocomplete for keywords, however, is not case-sensitive, which is good.  In case of multiple keywords that differ only by capitalization, it appears that the autocomplete suggests the _first_ matching (caps-insensitive) keyword.  For example, in the keyword table in the CKAN database, there are two keywords:
British Columbia
BRITISH COLUMBIA

When typing any form of this keyword:
brit
Brit
BRIT
bRiT
only the form British Columbia comes up as a suggestion.  This is good, as long as there is only one canonical form of each keyword (and once the keywords are cleaned up in issue https://github.com/genkimaps/gis-hub/issues/55, this will be the case). 

Another issue is that the keyword system (for Science keywords) does not prevent a user from entering a keyword with different capitalization.  Even if autocomplete suggests "important areas", there is nothing stopping the user from typing IMPORTANT AREAS, and it will be accepted as a new keyword.  ~~In theory, the frontend should catch this and replace IMPORTANT AREAS with important areas in the web browser.  This will require a lot of Javascript but it can be done.~~  This is now done in the CKAN backend, in the dfo plugin. See next comment.  

> Are there cases where two different forms of capitalization actually represent different things? 

Maybe, but for now we have decided on all lowercase.

**Comment by genkimaps** [comment]
All keywords are set to lowercase and deduplicated. 
`oceans, OCEANS, OCeaNS` is reduced to just `oceans`.  This is done for both science and GoC keywords, and it is independent of validating the GoC keywords (which was done in issue https://github.com/genkimaps/gis-hub/issues/22).

**Comment by cole-fields** [comment]
this is great, thanks.
