### ISSUE TITLE
Support 'Link' resource type

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#60]
~~Ensure only one uploaded zip file per dataset.~~ 

~~We tried having multiple uploads per dataset, and it created problems--when updating resources in the API, it seems that the downloadable status (url_type: "upload") gets overwritten if there is more than one file upload per dataset, and the link to download the second (or later) resource file will always end up pointing to the first downloadable file.  Any dataset that has more than one uploaded resource should be logged and passed on to the dataset publisher for correction.~~ 

This was a red herring.  There are not two uploaded files for the IA datasets; instead there is one uploaded URL placeholder with `url_type: upload` and another resource which is a _link_ to the IA docs, with a different URL. We want to allow this. 

CKAN supports creating a link resource (instead of uploading a file). However, there is no way to tell which type of resource is a link from the list of resources.  The appearance of the list of resources should clearly differentiate among:
1. upload placeholder with a green Download button, plus Manage
2. links with a Go to Link button, plus Manage
3. auto-generated layers/files with only a Manage button
This can be done by setting the `resource_type` metadata field (currently unused, and null for all resources) in ckanext-dfo, **and** setting the resource_type to 'Layer or File' for all detected layers in hub-geo-api. 

@cole-fields 
Go ahead and set the URL for the links in the IA datasets to https://www.gis-hub.ca/dataset/ia-documentation, you don't have to wait for this feature to be done.

**Comment by genkimaps** [comment]
Added support for the resource_type field in the CKAN DFO extension.  Specifically, I needed to make sure that the `resource_type` field is always populated.  If `resource_type` is always populated, we can use the resource templates to display different kinds of resources differently (see comment above).  This can be done by hooking into the IResourceController plugin interface, which looks straightforward. See docs here:

https://docs.ckan.org/en/2.8/extensions/plugin-interfaces.html#ckan.plugins.interfaces.IResourceController

However, the DFO extension already implements the IPackageController, which has many of the _same method signatures_ as IResourceController.  You must implement all of the methods and return something if necessary, even if you don't use that method in the plugin.  If you don't implement one or more methods, you will get a NotImplemented error, something like "NotImplemented: after_create"

...but not always. In the IResourceController, I missed a couple of methods that are only in that controller, not in the package controller.  This caused an error upstream, in one of the templates that tries to render packages (looks like it's an error with the package being None, but it's actually coming from one of the IResourceController methods that was missing). The error was: 

`File '/home/tk/ckan/ckan/templates/snippets/package_item.html', line 39 in block "heading_meta"`
`  {% if package.get('state', '').startswith('draft') %}`
`UndefinedError: 'None' has no attribute 'get'`

Once I fully implemented both the IResourceController and IPackageController methods, it works.

**Comment by genkimaps** [comment]
This is now done in the templates. Link resources appear distinct from Download resources and layer/files indexed from the data. See screenshot. Also the Link type and a default format 'link' are automatically set (in the CKAN `after_create()` method) whenever a link resource is created or updated.  See branch: https://github.com/genkimaps/gis-hub/tree/res-types

Prod is currently running on this branch, will merge with master once we're sure everything is working.

**Comment by genkimaps** [comment]
@cole-fields Added a section for Links to the documentation:  https://www.gis-hub.ca/docs#linking

**Comment by cole-fields** [comment]
this is great - I will add an issue on the gitlab gis-layers page to link the IA datasets to the separate resource. nice work, much cleaner.

**Comment by genkimaps** [comment]
Prod GIS hub is now on master, the branch for this issue has been merged into master. Closing this issue.
