### ISSUE TITLE
Backup metadata for datasets before update

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#64]
We want to dump the dataset's entire metadata record to a timestamped JSON file, then put it on Amazon S3. These files are quite small, so even with a lot of them, it won't use much cloud storage.  Only update the metadata record if it has changed since last update. Do this for an entire dataset at one time (not just for resources). 

In the ckanext-dfo extension, we need to hook into dataset_create/upate and resource_create/update.  We already have code in hub-geo-api that creates the metadata record; but it is Python3, while CKAN is python2, so will need to be run using an external CalledProcess.  Also need to add these features:
- check latest metadata backup, only update if needed
- save backup to Amazon S3

**Comment by genkimaps** [comment]
Look into CKAN revisions, aren't all changes already recorded internally?

**Comment by genkimaps** [comment]
@cole-fields  I created a storage bucket in amazon S3 for this, and dumped all of the existing metadata versions in there.  This is not yet connected to the core CKAN system, so only updates triggered by uploading a file (in the hub-geo-api backend) will be saved here. 

https://s3.console.aws.amazon.com/s3/buckets/meta-archive/?region=ca-central-1

**Comment by genkimaps** [comment]
@cole-fields This is now implemented and linked to the dataset update event in CKAN.  You should see the metadata snapshot posted to the Amazon S3 link (in the comment above) within a few seconds after updating a dataset/resource.  A snapshot will only be saved if there is a change in the metadata (if you just click Manage, don't change anything, and then click Update dataset, no backup will be created).

**Comment by cole-fields** [comment]
@genkimaps great! this is excellent and I think will be really useful when projects and datasets are revisited and maybe users need to reference the previous metadata.

**Comment by genkimaps** [comment]
Seems to be working as expected. Closing now.
