### ISSUE TITLE
7zip application download button

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#65]
One of the datasets on gis hub has a green 'Download Application' button instead of 'Download ZIP'.  Investigate and fix. 

@cole-fields which dataset is this? Can't find it.

**Comment by cole-fields** [comment]
it was here: https://www.gis-hub.ca/dataset/eezwaterarea

i set the state to 'deleted' in the postgres database and created a new dataset (https://www.gis-hub.ca/dataset/eez-waterarea) for it, copying over the metadata.  i think he originally had it in a shapefile and i put in into a file geodatabase

**Comment by cole-fields** [comment]
And the ‘board’ which is like a ‘project’ in github is here: https://gitlab.com/msea-projects/gis-hub/gis-hub-layers/-/boards

**Comment by genkimaps** [comment]
Closing this issue since the new EEZ dataset seems to be fine.
