### ISSUE TITLE
incorrect EPSG code listed on resource

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#66]
see https://www.gis-hub.ca/dataset/substrate20m

These are all in EPSG: 3005 (i double checked the download file). i even deleted the original resources and then re-uploaded. low priority, but maybe a bug? The proj name is correct, but EPSG code is not. 
![Capture](https://user-images.githubusercontent.com/52669482/73700583-c4920300-469b-11ea-808e-fb83c4217a40.PNG)

**Comment by genkimaps** [comment]
Closing this, duplicate of https://github.com/genkimaps/hub-geo-api/issues/9
