### ISSUE TITLE
Interface is green

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#74]
Why is this happening suddenly, this morning? 

Was anything done with the `paster color` command:
https://docs.ckan.org/en/2.8/maintaining/paster.html#color-create-or-remove-a-color-scheme

![image](https://user-images.githubusercontent.com/15989988/78866305-1c712f80-7a7a-11ea-8120-ebbe5f7e589c.png)

**Comment by genkimaps** [comment]
Looks like it was changed here:
https://www.gis-hub.ca/ckan-admin/config

**Comment by genkimaps** [comment]
Not this:
https://docs.ckan.org/en/2.8/maintaining/paster.html#color-create-or-remove-a-color-scheme
And nothing wrong with the templates.  The color scheme is stored in the database, in table `system_info`, column `ckan.main_css` which links to the default main.min.css, or one of the css in a different colour.

**Comment by cole-fields** [comment]
@genkimaps yes, I had changed it to green with https://www.gis-hub.ca/ckan-admin/config. 

there's a few pre-made colour themes and I was just testing them out.
