### ISSUE TITLE
Viewing dataset while logged out causes server error

### ISSUE THREAD

**Issue by genkimaps** [genkimaps/gis-hub#76]
If we try to view a dataset while logged out from CKAN, for example:
https://www.gis-hub.ca/dataset/test-01

We get a Server Error page. The CKAN logs show a very cryptic error, while loading the resources for the package (Dataset) in the backend:
`TypeError: 'NoneType' object has no attribute '__getitem__'`

Desired behavior: If logged out, accessing _any_ page should redirect to the login page. 

Is there a global "require login" setting for CKAN?  Relevant examples: 
https://stackoverflow.com/questions/57381878/requiring-login-on-ckan
https://stackoverflow.com/a/57211547/6502239
https://stackoverflow.com/questions/51069265/how-to-redirect-ckan-to-external-url-unless-authorized-or-signed-in/51223813#51223813

**Comment by cole-fields** [comment]
I don't receive that error message when logged out. It just prompts me to login

![image](https://user-images.githubusercontent.com/52669482/79610743-fec14d00-80ad-11ea-9887-d7c59a114a70.png)

**Comment by genkimaps** [comment]
@cole-fields You're right, this was something transient.
