### ISSUE TITLE
Cron job for weekly database backup

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#81]
@genkimaps this is a task I'll work on now that I have a better understanding of cron jobs. I manually to a backup weekly, but think a cron job would be appropriate.

* [x]  @cole-fields write shell script in `/home/tk/ckanext-dfo` to export ckan and datastore_default databases to `/tmp`
-  The only tricky part might be appending the date to the file (i.e. ckan.20200616.sql)
-  Ideally it would be nice to scp right to my external drive and the delete the files on `/tmp` automatically, but may not do doable
* [x]  @cole-fields chmod 755 script to give the shell permission to run the script
* [x]  @cole-fields edit  `/home/tk/ckan/REAME.conf.md` to note additional script
* [x]  @cole-fields edit  `/home/dfo/dfo-crontab` with additional command (weekly)
* [x]  @cole-fields check that it worked via `sudo cat /var/spool/cron/crontabs/dfo` (https://github.com/genkimaps/gis-hub/wiki/GIS-Hub-Admin-Guide)

**Comment by cole-fields** [comment]
can probably use windows task scheduler if i wanted to copy the backups automatically.

**Comment by cole-fields** [comment]
added commands to delete previous backups (if they exist) form /tmp directory. This script will run every Friday at midnight. User still needs to scp the backups to local or external drive.

**Comment by genkimaps** [comment]
@cole-fields  Looks good, I received an email from this, so it seems to be working
