### ISSUE TITLE
Update dataset list view

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#94]
- [x] include number of resources that are included in dataset
- [x] include created and updated date (similar to https://open.alberta.ca/opendata)

![image](https://user-images.githubusercontent.com/52669482/109050813-b049eb00-768e-11eb-8659-295fa72ac426.png)

**Comment by cole-fields** [comment]
decided not to include the created date, but could in the future. wanted to include the 'quality_control' field, but could not figure it out -- possibly address in future.

testing was done on https://github.com/genkimaps/gis-hub/tree/res-count and then merged w/master

**Comment by genkimaps** [comment]
@cole-fields What do you mean by "include the 'quality_control' field"? 
It should already be displayed for any dataset (certainly in the Edit view, and also in the dataset read view, unless the dataset was last created before that field was added to the schema, in which case it might be blank). 

The change you made in the template (which seems to have been reverted) should not be necessary.

**Comment by cole-fields** [comment]
@genkimaps these were updates made to the package_item.html template which renders the list of datasets on gis-hub.ca/dataset. I wanted to provide a bit more context about the datasets on this page (see the image below). I decided that included a few metadata fields like the published date, updated date, and number of resources would be helpful. I considered adding the quality control as well, but a) couldn't get it to work and b) thought it might become cluttered anyways.


![image](https://user-images.githubusercontent.com/52669482/110512788-61527b80-80ba-11eb-9072-bfbd21af0957.png)
