### ISSUE TITLE
enable cloudwatch 

### ISSUE THREAD

**Issue by cole-fields** [genkimaps/gis-hub#96]
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/gs_monitor_estimated_charges_with_cloudwatch.html#gs_creating_billing_alarm

- [x] on AWS console, enable cloudwatch
- [x] set up billing alerts
- [x] set up billing alarms
- [x] subscribe to alerts (3 email accounts my dfo and personal gmail, and @genkimaps gmail account)

**Comment by cole-fields** [comment]
Set up billing alarm if estimated charges exceed $100 USD over a 6 hour period.  Can easily be modified.

**Comment by cole-fields** [comment]
@genkimaps you'll receive a new subscription email from AWS. please subscribe. for billing alarms, they have to be created using the US East region and so that's why we saw insufficient data on the previous alarm. I will remove the old alarm.

**Comment by genkimaps** [comment]
@cole-fields OK, Subscription confirmed
